
#########################################################
# SCRIPT: 01_GGF_statistics.R
# TASK: This script generates the statistical figures of GGF
#########################################################


# PACKAGES ----------------------------------------------------------------
pacman::p_load(echarts4r)
pacman::p_load(htmlwidgets)


# 1. Prepare Data ---------------------------------------------------------
## Merged sample of GGF and listed company shareholders
Big10SH_GGF_nodupl <- readRDS(here("processed", "Big10SH-GGF_nodupl_20221001.rds"))

## Listed corporation info data
listed_corp_info <- readxl::read_xlsx(here("data", "corporate-info_20220804.xlsx"))
listed_corp_info <- mutate(listed_corp_info, Year = lubridate::year(EndDate))

## Calculate year distribution
year_distribution <- Big10SH_GGF_nodupl |> 
  filter(Year >= 2010) |> 
  count(Year) |> 
  mutate(Year = factor(Year)) 

## Calculate industry distribution
industry_distribution <- Big10SH_GGF_nodupl |> 
  count(Stkcd, Year) |> 
  left_join(y = listed_corp_info[, c("Symbol", "IndustryName", "Year")],
            by = c("Stkcd" = "Symbol", "Year")) |>  
  count(IndustryName) |> 
  filter(n > 25) |> 
  ungroup()


# 2. Plot Generation ------------------------------------------------------
## echarts4r configure
e_common(
  font_family = "times new roman",
  theme = NULL
)

## GGF year distribution bar plot
GGF_year_distribution <- year_distribution |> 
  e_charts(x = `Year`) %>% 
  e_x_axis(name = "年度", 
           axisLabel = list(fontSize = 16), 
           nameTextStyle = list(fontSize = 20)) |> 
  e_y_axis(name = "数量",
           axisLabel = list(fontSize = 16), 
           nameTextStyle = list(fontSize = 20)) |> 
  e_bar(serie = n, 
        name = "匹配样本量", 
        legend = FALSE,
        label = list(show = 'true', fontSize = 20, position = 'outside'))

## GGF industry distribution pie plot
GGF_indu_distribution <- industry_distribution %>% 
  arrange(-n) %>% 
  add_row(IndustryName = "其他行业", 
          n = nrow(Big10SH_GGF_nodupl) - sum(industry_distribution$n)) %>% 
  mutate(IndustryName = paste0(IndustryName, " (", n, ")")) %>% 
  e_charts(x = IndustryName) %>%
  e_pie(serie = n, 
        name = "数量", 
        legend = FALSE, 
        label = list(fontSize = 18))

## Save to plot files
######################## Tip ########################
# Plots generated by echarts4r cannot be converted directly to the satisfied
#   png format without interactive operations. So save rds and html files instead
#####################################################
saveRDS(object = GGF_year_distribution, 
        file = here("results", "figures", "GGF-year-distribution.rds"))
saveRDS(object = GGF_indu_distribution, 
        file = here("results", "figures", "GGF-indu-distribution.rds"))
htmlwidgets::saveWidget(widget = GGF_year_distribution, 
                        file = "results/figures/GGF-year-distribution.html")  
htmlwidgets::saveWidget(widget = GGF_indu_distribution, 
                        file = "results/figures/GGF-indu-distribution.html")  

### EOF
